{
 "title": "CamundaCon",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(atomix_role, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   },
   { "name": "memory_state", "query": "committed, reserved" }
  ]
 },
 "panels": [
  {
   "title": "Process Instance Events per second (range = 1m)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[$__rate_interval])) by (action)"
    }
   ]
  },
  {
   "title": "Job events per second (range = 1m)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (action)",
     "legendFormat": "Stream Processor"
    }
   ]
  },
  {
   "title": "Process instance creation per second",
   "type": "timeseries",
   "description": "Shows the process instance creation rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_executed_instances_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Process instance creation {{namespace}}"
    }
   ]
  },
  {
   "title": "Process instance completion per second",
   "type": "timeseries",
   "description": "Shows the process instance completion rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_executed_instances_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"completed\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Process instance completion {{namespace}}"
    }
   ]
  },
  {
   "title": "Job creation per second",
   "type": "timeseries",
   "description": "Shows the Job creation rate over all partitions in the namespace",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"created\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Job creation {{namespace}}"
    }
   ]
  },
  {
   "title": "Job completion per second",
   "type": "timeseries",
   "description": "Shows the Job completion rate over all partitions in the namespace.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"completed\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Job completion {{namespace}}"
    }
   ]
  },
  {
   "title": "In flight Requests",
   "type": "timeseries",
   "description": "Current number of request inflight per partition.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(zeebe_backpressure_inflight_requests_count{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) by (partition)",
     "legendFormat": "Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Total Dropped Requests",
   "type": "timeseries",
   "description": "The rate of requests dropped due to backpressure per partition.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_dropped_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]) ) by (partition)",
     "legendFormat": "Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Backpressure Requests Limit",
   "type": "timeseries",
   "description": "Current limit for number of inflight requests per partition.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(zeebe_backpressure_requests_limit{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})by (partition)",
     "legendFormat": "Partition: {{partition}}"
    }
   ]
  }
 ]
}