import fs from 'fs';
import path from 'path';

// Hardens the generated `buildClientParams` against prototype pollution
// (CVE-2026-48819 / GHSA-hhx9-57xq-r5rw).
//
// src/gen/core/params.gen.ts is a runtime template copied verbatim out of
// @hey-api/openapi-ts into the generated SDK, so it ships to consumers. In the
// version pinned on this branch it initialises each slot with a plain object
// literal:
//
//   const params: Params = { body: {}, headers: {}, path: {}, query: {} };
//
// `buildClientParams` then writes caller-controlled keys into those slots — both
// via the `$<slot>_` extra-prefix branch and via `allowExtra`. A key of
// `$query___proto__` (or a bare `__proto__` under `allowExtra`) therefore reaches
// `params.query['__proto__'] = value`, which invokes the `__proto__` setter and
// substitutes the object's prototype with caller-supplied data. Applications that
// forward user-supplied request parameters into a generated client method —
// proxies, BFF layers, API gateways — are reachable.
//
// Upstream fixed this in 0.97.3 by giving each slot a null prototype, which makes
// `__proto__` an ordinary own property instead of a setter call. This script
// applies exactly that upstream change, so the output matches what a future
// generator bump would produce and this becomes a silent no-op at that point. The
// write sites are deliberately left alone — upstream did not change them, and the
// null prototype is what removes the sink.
//
// This is a value-level change inside a function body: the `Params` interface and
// every exported type are untouched, so the published type surface is unchanged.
//
// This script should be invoked after openapi generation.
//
// Advisory: https://github.com/advisories/GHSA-hhx9-57xq-r5rw

const root = process.cwd();
const paramsGenPath = path.join(root, 'src/gen/core/params.gen.ts');

if (!fs.existsSync(paramsGenPath)) {
  console.error('[harden-client-params] params.gen.ts not found');
  process.exit(1);
}

const source = fs.readFileSync(paramsGenPath, 'utf8');

const SLOTS = ['body', 'headers', 'path', 'query'] as const;

// Already hardened (or generated by >= 0.97.3): nothing to do.
const alreadyHardened = SLOTS.every((slot) =>
  new RegExp(`\\b${slot}:\\s*Object\\.create\\(null\\)`).test(source)
);

if (alreadyHardened) {
  console.log('[harden-client-params] Slots already use Object.create(null) — nothing to patch');
  process.exit(0);
}

// Narrow the rewrite to the `const params: Params = { ... };` initialiser so we
// cannot touch an unrelated object literal elsewhere in the file.
const initialiser = /(const params: Params = \{)([\s\S]*?)(\n\s*\};)/;
const match = source.match(initialiser);

if (!match) {
  console.error(
    '[harden-client-params] Could not locate the `const params: Params = {...}` initialiser ' +
      'in src/gen/core/params.gen.ts. The generator output shape has changed — review the ' +
      'template against GHSA-hhx9-57xq-r5rw before releasing.'
  );
  process.exit(1);
}

const [, open, body, close] = match;

let patchedBody = body;
let replaced = 0;
for (const slot of SLOTS) {
  const empty = new RegExp(`(\\b${slot}:\\s*)\\{\\}`);
  if (!empty.test(patchedBody)) continue;
  patchedBody = patchedBody.replace(empty, `$1Object.create(null)`);
  replaced++;
}

if (replaced !== SLOTS.length) {
  console.error(
    `[harden-client-params] Expected to harden ${SLOTS.length} slots but matched ${replaced}. ` +
      'Refusing to emit a partially hardened params.gen.ts — review the generator output.'
  );
  process.exit(1);
}

const patched = source.replace(initialiser, `${open}${patchedBody}${close}`);
fs.writeFileSync(paramsGenPath, patched, 'utf8');
console.log(
  `[harden-client-params] Hardened ${replaced} params slot(s) with Object.create(null) in params.gen.ts`
);
