#!/usr/bin/env tsx
/**
 * Writes src/runtime/version.ts containing exported packageVersion constant
 * sourced from package.json. Deterministic & idempotent; only rewrites when
 * version differs.
 */
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const pkgPath = path.join(root, 'package.json');
const outPath = path.join(root, 'src', 'runtime', 'version.ts');

function main() {
  if (!fs.existsSync(pkgPath)) {
    console.error('[version-sync] package.json not found');
    process.exit(1);
  }
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const version = pkg.version || '0.0.0';
  const banner = '// @generated by scripts/write-version-constant.ts\n';
  const content = `${banner}export const packageVersion = '${version}';\n`;
  if (fs.existsSync(outPath)) {
    const current = fs.readFileSync(outPath, 'utf8');
    if (current === content) {
      console.log('[version-sync] version.ts already up-to-date');
      return;
    }
  }
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`[version-sync] wrote version.ts -> ${version}`);
}

main();
